#!/usr/bin/env node

/**
 * NDIT SVG Icons Builder
 *
 * Compiles individual SVG source files from icon-svg/ into a single
 * JavaScript module (dist/ndit-icons.js) that registers with
 * Home Assistant's custom icon system.
 *
 * Unlike monochrome icon packs (which extract a single <path d="...">),
 * this builder preserves the full SVG inner content — gradients, multiple
 * paths, classes — so multi-color icons render correctly.
 *
 * Usage:
 *   node build-icons.js
 *
 * The generated JS file registers icons under the "ndit:" prefix.
 * Example:  ndit:brand-streaming-disney-plus
 */

const fs = require("fs");
const path = require("path");

const SVG_SOURCE_DIR = path.join(__dirname, "icon-svg");
const OUTPUT_DIR = path.join(__dirname, "dist");
const OUTPUT_FILE = path.join(OUTPUT_DIR, "ndit-icons.js");
const ICON_PREFIX = "ndit";

// ---------------------------------------------------------------------------
// Collect all .svg files recursively
// ---------------------------------------------------------------------------
function collectSvgFiles(dir) {
  let results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(collectSvgFiles(fullPath));
    } else if (entry.isFile() && entry.name.endsWith(".svg")) {
      results.push(fullPath);
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// Parse an SVG file: extract viewBox and inner content
// ---------------------------------------------------------------------------
function parseSvg(filePath) {
  const raw = fs.readFileSync(filePath, "utf-8").trim();

  // Extract viewBox
  const viewBoxMatch = raw.match(/viewBox=["']([^"']+)["']/);
  if (!viewBoxMatch) {
    console.warn(`  ⚠  Skipping ${filePath} — no viewBox found`);
    return null;
  }

  // Extract everything between <svg ...> and </svg>
  const innerMatch = raw.match(/<svg[^>]*>([\s\S]*)<\/svg>/i);
  if (!innerMatch) {
    console.warn(`  ⚠  Skipping ${filePath} — could not parse SVG content`);
    return null;
  }

  // Derive icon name from filename (strip .svg extension)
  const iconName = path.basename(filePath, ".svg");

  return {
    name: iconName,
    viewBox: viewBoxMatch[1],
    content: innerMatch[1].trim(),
  };
}

// ---------------------------------------------------------------------------
// Build the output JS
// ---------------------------------------------------------------------------
function buildIconsJs(icons) {
  // Default color scheme applied via CSS classes
  const defaultColors = {
    "icon-primary": "#ffffff",
    "gradient-start": "#ffffff",
    "gradient-mid": "#00ffff",
    "gradient-end": "#0000ff",
  };

  const iconEntries = icons
    .map((icon) => {
      // Escape backticks and backslashes for template literal safety
      const safeContent = icon.content
        .replace(/\\/g, "\\\\")
        .replace(/`/g, "\\`")
        .replace(/\$/g, "\\$");
      return `  "${icon.name}": { viewBox: "${icon.viewBox}", content: \`${safeContent}\` }`;
    })
    .join(",\n");

  return `/**
 * NDIT Icons for Home Assistant
 * Auto-generated by build-icons.js — do not edit manually
 *
 * Prefix:  ${ICON_PREFIX}:
 * Icons:   ${icons.length}
 * Built:   ${new Date().toISOString()}
 *
 * Usage in HA:
 *   icon: ${ICON_PREFIX}:brand-streaming-disney-plus
 *
 * Color customization via card-mod:
 *   card_mod:
 *     style:
 *       ha-icon:
 *         $: |
 *           .icon {
 *             --ndit-icon-primary: #ff0000;
 *             --ndit-gradient-start: #ffffff;
 *             --ndit-gradient-mid: #00ffff;
 *             --ndit-gradient-end: #0000ff;
 *           }
 */

const NDIT_ICONS = {
${iconEntries}
};

const DEFAULT_COLORS = ${JSON.stringify(defaultColors, null, 2)};

function getIcon(name) {
  const icon = NDIT_ICONS[name];
  if (!icon) return null;

  // Apply default colors via class-based styling
  // Users can override via CSS custom properties (--ndit-icon-primary, etc.)
  let content = icon.content;

  // Inject fill values for class-based elements
  content = content
    .replace(/class="icon-primary"/g,  'fill="var(--ndit-icon-primary, ${defaultColors["icon-primary"]})"')
    .replace(/class="icon-gradient"/g, 'fill="url(#' + name + '-grad)"')
    .replace(/class="gradient-start"/g, 'stop-color="var(--ndit-gradient-start, ${defaultColors["gradient-start"]})"')
    .replace(/class="gradient-mid"/g,   'stop-color="var(--ndit-gradient-mid, ${defaultColors["gradient-mid"]})"')
    .replace(/class="gradient-end"/g,   'stop-color="var(--ndit-gradient-end, ${defaultColors["gradient-end"]})"');

  return {
    viewBox: icon.viewBox,
    content: content,
  };
}

window.customIconsets = window.customIconsets || {};
window.customIconsets["${ICON_PREFIX}"] = getIcon;

console.info(
  "%c NDIT Icons %c loaded ${icons.length} icon(s) ",
  "color: white; background: #3b82f6; font-weight: bold; padding: 2px 6px; border-radius: 4px 0 0 4px;",
  "color: #3b82f6; background: #eff6ff; padding: 2px 6px; border-radius: 0 4px 4px 0;"
);
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
function main() {
  console.log("🔨 NDIT Icons Builder\n");

  if (!fs.existsSync(SVG_SOURCE_DIR)) {
    console.error(`❌ Source directory not found: ${SVG_SOURCE_DIR}`);
    process.exit(1);
  }

  const svgFiles = collectSvgFiles(SVG_SOURCE_DIR);
  console.log(`📂 Found ${svgFiles.length} SVG file(s) in ${SVG_SOURCE_DIR}\n`);

  if (svgFiles.length === 0) {
    console.error("❌ No SVG files found. Add icons to icon-svg/ and try again.");
    process.exit(1);
  }

  const icons = [];
  for (const file of svgFiles) {
    const icon = parseSvg(file);
    if (icon) {
      icons.push(icon);
      const relPath = path.relative(SVG_SOURCE_DIR, file);
      console.log(`  ✅ ${icon.name}  (${relPath})`);
    }
  }

  console.log("");

  if (icons.length === 0) {
    console.error("❌ No valid icons parsed. Check your SVG files.");
    process.exit(1);
  }

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const jsContent = buildIconsJs(icons);
  fs.writeFileSync(OUTPUT_FILE, jsContent, "utf-8");

  console.log(`✅ Build completed`);
  console.log(`📁 Generated file: ${path.relative(__dirname, OUTPUT_FILE)}`);
  console.log(`🔢 Total icons: ${icons.length}`);
  console.log(`🏷️  Prefix: ${ICON_PREFIX}:`);
}

main();
