#!/usr/bin/env node

/**
 * build-icons.js
 *
 * Scans icons/ directory for SVG files, extracts <path d="..."> data,
 * and generates src/icons-map.ts with all icons.
 *
 * Directory structure:
 *   icons/brands/streaming/disney-plus.svg  → ndit:brand-streaming-disney-plus
 *   icons/brands/streaming/netflix.svg      → ndit:brand-streaming-netflix
 *
 * Naming convention:
 *   icons/<category>/<subcategory>/<name>.svg
 *   becomes: <category>-<subcategory>-<name>
 *
 * Each SVG should ideally be a single-path icon. If the SVG has multiple
 * <path> elements, their d attributes are combined into a single path string.
 *
 * Keywords can be embedded in a <desc> tag inside the SVG:
 *   <desc>streaming video disney movies</desc>
 */

const fs = require("fs");
const path = require("path");

const ICONS_DIR = path.resolve(__dirname, "..", "icons");
const OUTPUT_FILE = path.resolve(__dirname, "..", "src", "icons-map.ts");

/**
 * Recursively find all .svg files in a directory
 */
function findSvgFiles(dir, files = []) {
  if (!fs.existsSync(dir)) {
    console.warn(`Warning: Directory ${dir} does not exist`);
    return files;
  }
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      findSvgFiles(fullPath, files);
    } else if (entry.isFile() && entry.name.endsWith(".svg")) {
      files.push(fullPath);
    }
  }
  return files;
}

/**
 * Extract all <path d="..."> values from SVG content
 */
function extractPaths(svgContent) {
  const paths = [];
  // Match all path d attributes (handles both single and double quotes)
  const pathRegex = /<path[^>]*\bd=["']([^"']+)["'][^>]*\/?>/gi;
  let match;
  while ((match = pathRegex.exec(svgContent)) !== null) {
    paths.push(match[1].trim());
  }
  return paths.join(" ");
}

/**
 * Extract viewBox from SVG content
 */
function extractViewBox(svgContent) {
  const match = svgContent.match(/viewBox=["']([^"']+)["']/i);
  return match ? match[1] : null;
}

/**
 * Extract keywords from <desc> tag
 */
function extractKeywords(svgContent) {
  const match = svgContent.match(/<desc[^>]*>([^<]+)<\/desc>/i);
  if (match) {
    return match[1]
      .trim()
      .split(/[\s,]+/)
      .filter((k) => k.length > 0);
  }
  return [];
}

/**
 * Convert file path to icon name
 * icons/brands/streaming/disney-plus.svg → brand-streaming-disney-plus
 */
function filePathToIconName(filePath) {
  const relative = path.relative(ICONS_DIR, filePath);
  const parts = relative.replace(/\.svg$/i, "").split(path.sep);

  // Singularize first directory (brands → brand, devices → device)
  if (parts.length > 0 && parts[0].endsWith("s")) {
    parts[0] = parts[0].slice(0, -1);
  }

  return parts.join("-").toLowerCase();
}

// --- Main ---

console.log("🎨 NDIT Icons - Building icon map...\n");

const svgFiles = findSvgFiles(ICONS_DIR);

if (svgFiles.length === 0) {
  console.warn("⚠️  No SVG files found in icons/ directory");
  console.log("   Place SVG files in icons/<category>/<name>.svg");
  console.log("   Example: icons/brands/streaming/netflix.svg\n");
}

const icons = {};
const errors = [];

for (const filePath of svgFiles) {
  const iconName = filePathToIconName(filePath);
  const svgContent = fs.readFileSync(filePath, "utf-8");

  const pathData = extractPaths(svgContent);
  if (!pathData) {
    errors.push(`  ✗ ${iconName}: no <path> elements found`);
    continue;
  }

  const viewBox = extractViewBox(svgContent);
  const keywords = extractKeywords(svgContent);

  icons[iconName] = {
    path: pathData,
    viewBox: viewBox || "0 0 24 24",
    keywords,
  };

  console.log(`  ✓ ${iconName}${viewBox ? ` (${viewBox})` : ""}`);
}

if (errors.length > 0) {
  console.log("\nWarnings:");
  errors.forEach((e) => console.log(e));
}

// Generate TypeScript output
const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: npm run build:icons
 * Generated at: ${new Date().toISOString()}
 * Total icons:  ${Object.keys(icons).length}
 *
 * To add new icons:
 *   1. Place your SVG in icons/<category>/<icon-name>.svg
 *   2. Run: npm run build:icons
 *   3. The icon will be available as ndit:<category>-<icon-name>
 */

export interface IconDefinition {
  path: string;
  viewBox?: string;
  keywords?: string[];
}

export const NDIT_ICONS_MAP: Record<string, IconDefinition> = ${JSON.stringify(icons, null, 2)};
`;

// Ensure output directory exists
const outputDir = path.dirname(OUTPUT_FILE);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(OUTPUT_FILE, output, "utf-8");

console.log(`\n✅ Generated ${OUTPUT_FILE}`);
console.log(`   ${Object.keys(icons).length} icons built successfully\n`);
