/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: npm run build:icons
 * Generated at: 2026-02-06T18:53:07.995Z
 * Total icons:  1
 *
 * To add new icons:
 *   1. Place your SVG in icons/<category>/<icon-name>.svg
 *   2. Run: npm run build:icons
 *   3. The icon will be available as ndit:<category>-<icon-name>
 */

export interface IconDefinition {
  path: string;
  viewBox?: string;
  keywords?: string[];
}

export const NDIT_ICONS_MAP: Record<string, IconDefinition> = {
  "brand-streaming-sample-test": {
    "path": "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z",
    "viewBox": "0 0 24 24",
    "keywords": [
      "streaming",
      "video",
      "test",
      "sample"
    ]
  }
};
