/** ndit-icons/src/ndit-icons.ts
 * NDIT Icons - Custom icon set for Home Assistant
 *
 * This file is the main entry point for the icon library.
 * Icon data is auto-generated by the build script into icons-map.ts
 *
 * Usage in Home Assistant:
 *   icon: ndit:brand-disney-plus
 *   icon: ndit:brand-netflix
 */

import { NDIT_ICONS_MAP } from "./icons-map";

const ICONSET_PREFIX = "ndit";

interface IconResult {
  path: string;
  viewBox?: string;
}

interface IconListEntry {
  name: string;
  keywords?: string[];
}

async function getIcon(name: string): Promise<IconResult> {
  const icon = NDIT_ICONS_MAP[name];
  if (icon) {
    return {
      path: icon.path,
      viewBox: icon.viewBox || "0 0 24 24",
    };
  }
  console.warn(`NDIT Icons: icon "${name}" not found`);
  return { path: "" };
}

async function getIconList(): Promise<IconListEntry[]> {
  return Object.entries(NDIT_ICONS_MAP).map(([name, data]) => ({
    name,
    keywords: data.keywords || [],
  }));
}

// Register with Home Assistant's icon system
(window as any).customIconsets = (window as any).customIconsets || {};
(window as any).customIconsets[ICONSET_PREFIX] = getIcon;

// Register with HA's icon picker (for searchable icons in the UI)
(window as any).customIcons = (window as any).customIcons || {};
(window as any).customIcons[ICONSET_PREFIX] = { getIcon, getIconList };

console.info(
  `%c NDIT Icons %c loaded ${Object.keys(NDIT_ICONS_MAP).length} icons `,
  "color: white; background: #4CAF50; font-weight: bold;",
  "color: #4CAF50; background: transparent;"
);

